### ISSUE TITLE
StdHepReader.cc not assigning generator status properly

### ISSUE THREAD

**Issue by scipp-ilcadmin** [iLCSoft/Marlin#1]
Hello, 

We have discovered that the driver responsible for converting a stdhep file to a collection of MCParticles within Marlin (StdHepReader.cc) is assigning a generator status of 1 (final state) to EVERY particle in the event. 

When we analyze the file at the stdhep level (using the StdhepEvent class in the LCSim framework), we see proper generator status assignment. However, after we ran this file through the StdHepReader which converts it to collections of MCParticles, we discovered that each particles had a generator status of 1 (using the getGeneratorStatus() function.) 

This flawed driver can be found here: /cvmfs/ilc.desy.de/sw/x86_64_gcc44_sl6/v01-17-09/Marlin/v01-08/source/src/StdHepReader.cc

I wanted to draw attention to this issue and point out that the LCStdHepReader found in the plcio workspace, works great and can be found here: https://stash.desy.de/projects/IL/repos/plcio/browse/source/utilities/LCStdHepReader.cc

Jane Shtalenkova
yshtalen@ucsc.edu

**Comment by gaede** [comment]
I cannot reproduce or understand this problem. The StdHepReader processor does not set the generator status at all but rather uses the [LCStdHepReader.cc](https://github.com/iLCSoft/LCIO/blob/master/src/cpp/src/UTIL/LCStdHepRdr.cc) from LCIO ( which is the original implementation that has been ported to plcio).  Can you provide an example stdhep file where this problem occurs ?

**Comment by petricm** [comment]
No response from issue opener
