### ISSUE TITLE
Error when running Marlin

### ISSUE THREAD

**Issue by luisaleperez** [iLCSoft/Marlin#9]
Hi all,

I am using the latest version of LDConfig (HEAD-2017-04-06). I just ran the example in the README file, that is,

Simulation:
ddsim --inputFiles ./bbudsc_3evt.stdhep --outputFile=./bbudsc_3evt.slcio --compactFile $lcgeo_DIR/ILD/compact/ILD_l1_v01/ILD_l1_v01.xml --steeringFile=./ddsim_steer.py

Creation of gear file
convertToGear default $lcgeo_DIR/ILD/compact/ILD_l1_v01/ILD_l1_v01.xml gear_ILD_l1_v01_dd4hep.xml

and reconstruction
Marlin bbudsc_3evt_stdreco_dd4hep.xml --global.GearXMLFile=gear_ILD_l1_v01_dd4hep.xml  --InitDD4hep.DD4hepXMLFile=$lcgeo_DIR/ILD/compact/ILD_l1_v01/ILD_11_v01.xml

Everything runs well but the last one (reconstruction) which gives the following error,

Error in <TCling::RegisterModule>: cannot find dictionary module dict_rdict.pcm

 ***********************************************
 A runtime error occured - (uncaught exception):
      marlin::ParseException: XMLParser::parse error in file [bbudsc_3evt_stdreco_dd4hep.xml, row: 0, col: 0] : Failed to open file
 Marlin will have to be terminated, sorry.
 ***********************************************

Does anyone knows if there is a problem with Marlin? Does something changed recently? For example, the way of giving the inputs?

Cheers,

  Alejandro

**Comment by luisaleperez** [comment]
sorry, the actual error message when running the reconstruction is,


[log.log.txt](https://github.com/iLCSoft/Marlin/files/910854/log.log.txt)

**Comment by shaojunlu** [comment]
- Tested, and  may run the reconstruction as the README without this "Unknwon command line parameter overwrite ( spelling !?)" problem.
    - Could you check your local steering " bbudsc_3evt_stdreco_dd4hep.xml"?
    - Anything changed at line 183 by yourself?
    - https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/lcgeo_current/bbudsc_3evt_stdreco_dd4hep.xml#L183

 - Error in TCling::RegisterModule: cannot find dictionary module dict_rdict.pcm
   - this is another issue,
      - https://github.com/lcfiplus/LCFIPlus/issues/17
   - it will be fixed by this pull 
      - https://github.com/lcfiplus/LCFIPlus/pull/18
   - this is not the problem for what you have seen here.

**Comment by luisaleperez** [comment]
Thanks. My mistake. I modified the by mistake this line on the file. I just recuperated the one in the HEAD and it works now.

Sorry for the noise.
